### ISSUE TITLE
There are no tests

### ISSUE THREAD

**Issue by Glutexo** [Glutexo/onigumo#10]
`Onigumo.download` already does stuff. Test it!

Test that it downloads a file and writes it to `body.html`. Simple as that.

**Comment by Glutexo** [comment]
First, I would keep the test touching the real internet. But as a next step, mocking should be done. Found a nice article on this topic: https://thoughtbot.com/blog/mocking-and-faking-external-dependencies-in-elixir-tests

**Comment by nappex** [comment]
Let's discuss about **think about mock as noun rather than verb**

see:
* http://blog.plataformatec.com.br/2015/10/mocks-and-explicit-contracts/
* https://www.thegreatcodeadventure.com/elixir-test-mocking-with-mox/
