### ISSUE TITLE
🏗 Move File cwd to Onigumo.CLI

### ISSUE THREAD

**Issue by Glutexo** [Glutexo/onigumo#119]
The command line usage brings in the concept of a current working directory. The CWD does not make sense for a hypothetical GUI or web application. In the case of library usage, the parent application has an interface and determines the working directory for Onigumo.

Moving the working path [determination](https://github.com/Glutexo/onigumo/blob/a7d27a5985944247016302758644a9c3e9f863a5/lib/onigumo.ex#L9) to the CLI [module](https://github.com/Glutexo/onigumo/blob/a7d27a5985944247016302758644a9c3e9f863a5/lib/onigumo_cli.ex) brings another benefit in making the [main](https://github.com/Glutexo/onigumo/blob/a7d27a5985944247016302758644a9c3e9f863a5/lib/onigumo.ex#L6) function testable (#56). It prevents the usage of `:tmp_dir` in the tests.

**Comment by Glutexo** [comment]
@nappex You felt that the description is insufficient for you to grok the idea. Is it still valid? Do you need more information?

**Comment by Glutexo** [comment]
Imagine (Dragons) you have a GUI application. You run it via its icon, the app opens its window, and you use it. You weren’t in any directory because you were not on a command line. You’d instead use a directory widget to pick a folder.

See the attached PyCharm’s New Project dialog. It offers you a reasonable value (your home directory), but it would not make sense to put there whatever the process in the background considers its “current working directory.”

<img width="815" alt="Screenshot" src="https://user-images.githubusercontent.com/1161096/180985744-c32a4c5f-0908-49a1-b27e-a5376ba6c7c8.png">

Pardon my Japanese. I hope the UI is still understandable.

**Comment by nappex** [comment]
I got it!
