### ISSUE TITLE
Rename Onigumo.CLI to Onigumo.Cli

### ISSUE THREAD

**Issue by Glutexo** [Glutexo/onigumo#120]
For consistency with _HttpPoison_. I believe acronyms should behave as words in identifiers. In the snake case, it would be `cli`, not `c_l_i`.

**Comment by nappex** [comment]
i am not sure if i understood it well

**Comment by Glutexo** [comment]
It’s a long-running dilemma how to treat acronyms in camel-case identifiers. Use all caps, or downcase the letters? I like the latter more because it is more consistent, less confusing, and convertible to other cases.

Imagine a module called “CLI HTTP.” Named “CLIHTTP,” it is unclear where the word boundary is. In the snake-case, it would bear the name “cli_http,” but if converted automatically, it would become “c_l_i_h_t_t_p.” Because of that, I feel that “CliHttp” would be a better fit for the camel-case. The capital letters are delimiters, a replacement for dashes/underscores; they don’t carry the original semantic.
