### ISSUE TITLE
Alternative execution

### ISSUE THREAD

**Issue by nappex** [Glutexo/onigumo#13]
Use **escript**

* https://medium.com/blackode/writing-the-command-line-application-in-elixir-78a8d1b1850
* https://elixirschool.com/en/lessons/intermediate/escripts
* https://hexdocs.pm/mix/main/Mix.Tasks.Escript.Build.html
* https://blog.kstaykov.eu/dev/building-elixir-cli-app/
* https://whatdidilearn.info/2017/12/10/writing-command-line-app-in-elixir.html

* https://zorbash.com/post/building-command-line-applications-with-elixir/

**Comment by Glutexo** [comment]
Fixed by 4c73e5fe09290e2043aa685d7263a32fbfbfdaa2.
