### ISSUE TITLE
Parse args from CLI with `OptionParser.parse`

### ISSUE THREAD

**Issue by nappex** [Glutexo/onigumo#162]
Currently, we parse CLI args and options just with pattern matching #145. It will be nice if we parse args from CLI by built-in module `OptionParse` check [official docs](https://hexdocs.pm/elixir/OptionParser.html#parse/2) or [tutorial - elixir school](https://elixirschool.com/en/lessons/intermediate/escripts#parsing-args-1). This approach ensure to handle errors more elegant with help message and so on. Currently we get some ugly error. It is not very user friendly interface.

**Comment by Glutexo** [comment]
I completely agree!

**Comment by nappex** [comment]
Solve this before issue #182!
