### ISSUE TITLE
♻️ Improve module naming and directory structure

### ISSUE THREAD

**Issue by Glutexo** [Glutexo/onigumo#163]
All things Onigumo need to be inside the _Onigumo_ namespace to avoid name clashes. The Mix [project](https://github.com/Glutexo/onigumo/blob/076353f9bc5f7511181b2a5990ea2e75cd624715/mix.exs) itself is _Onigumo.MixProject_. **No submodules should pollute the global namespace.** That results in the following steps:

- [ ] Move the [_Downloader_](https://github.com/Glutexo/onigumo/blob/076353f9bc5f7511181b2a5990ea2e75cd624715/lib/onigumo_downloader.ex) module under a new _Kernel_ namespace.
- [ ] Move the [_Hash_](https://github.com/Glutexo/onigumo/blob/076353f9bc5f7511181b2a5990ea2e75cd624715/lib/hash.ex) module too into Onigumo.Kernel.
- [ ] Put the [_HTML_](https://github.com/nappex/onigumo/blob/af9da826466bb47486189b5330368350410c41a4/lib/spider_html.ex) module from #87 into _Onigumo.Spider_.

**Comment by nappex** [comment]
There is a [link](https://ulisses.dev/elixir/2022/03/04/elixir-modules-files-directories-and-naming-conventions.html) to blog where a guy describes his opinion about files and modules naming conventions.

**Comment by Glutexo** [comment]
Regarding the [_Hash_](https://github.com/Glutexo/onigumo/blob/076353f9bc5f7511181b2a5990ea2e75cd624715/lib/hash.ex) module, I am thinking of a _Utilities_ subnamespace. Having the core three pillars ([_Downloader_](https://github.com/Glutexo/onigumo/blob/076353f9bc5f7511181b2a5990ea2e75cd624715/lib/onigumo_downloader.ex), _Operator_, [_Parser_](https://github.com/Glutexo/onigumo/pull/146)) separated from auxiliary modules seems elegant, but an overly complex structure brings its issues too. It would look like this:

- _Onigumo.Kernel.Downloader_, _Onigumo.Kernel.Operator_, _Onigumo.Kernel.Parser_, _Onigumo.Kernel.Utilities.Hash_ or
- _Onigumo.Kernel.Core.Downloader_, _Onigumo.Kernel.Core.Operator_, and _Onigumo.Kernel.Core.Parser_, _Onigumo.Kernel.Utilities.Hash_. _Kernel.Core_ sounds fishy: I’d rather see _Onigumo.Onigumo.Core_ or _Onigumo.Onigumo.Kernel_.

Seeing it live, I find a flat structure less confusing: _Onigumo.Kernel.Downloader_, _Onigumo.Kernel.Operator_, _Onigumo.Kernel.Parser_, _Onigumo.Kernel.Hash_. We can revisit this when more modules are in place, but even with dozens of modules, a flat structure is still clear enough.

What do you think, @nappex?
