### ISSUE TITLE
Specify root path (--working-dir) by CLI argument

### ISSUE THREAD

**Issue by Glutexo** [Glutexo/onigumo#182]

**Comment by nappex** [comment]
@Glutexo yes, absolutely. I agree with that opinion. Only one thought, I d like keep the option to change this default behaviour by another destination if the taste of user will be diff...
We can begin with not required cli parameter?!?
Then we can do some configuration file in future if we ll have more options to set.

**Comment by nappex** [comment]
We hit the problem with test when we need to change the current working directory to check, content of working directory. We use `tmp_dir` for purpose of testing, but when the current directory is constant we can not reach the content of `tmp_dir` then.

**Comment by nappex** [comment]
Final implementation should looks like that:

1. if not specified working dir by default current is used
2. You can specify working dir by your taste anywhere you have the permission to
3. Always validate state of choosed working dire if the dir is suitable for onigumo outputs..

**Comment by Glutexo** [comment]
https://github.com/Glutexo/onigumo/issues/162

**Comment by nappex** [comment]
Consider the name `--working-dir` for the option

**Comment by Glutexo** [comment]
Just found that [Meson](https://mesonbuild.com) (a build system) uses `-C` for a working directory.

```
  -C WD                                         directory to cd into before running
```

If you find any other examples, drop them here, please.

**Comment by nappex** [comment]
> Just found that [Meson](https://mesonbuild.com) (a build system) uses `-C` for a working directory.
> 
> ```
>   -C WD                                         directory to cd into before running
> ```
> 
> If you find any other examples, drop them here, please.

Nice catch cowboy! 🤠 

I am little bit confused by sentence `directory to cd`, directory to current directory?!? That's a little bit confusing. Anyway big `C` looks great as `--current-working-dir`. But for the long version I may keep just the `--working-directory`

**Comment by Glutexo** [comment]
Tar has:

```
-C <dir>  Change to <dir> before processing remaining files
```
