### ISSUE TITLE
Use CLI `component` as positional argument

### ISSUE THREAD

**Issue by nappex** [Glutexo/onigumo#188]
We could consider updating the CLI usage from:

`./onigumo --component Downloader --working-dir ~/wd/`

to

`./onigumo Downloader --working-dir ~/wd/`

**Comment by Glutexo** [comment]
Well, this is already the case. The current raw (non-OptionParser) solution takes one positional argument that is the component. There is no named argument `--component`. 🤷🏻‍♂️
