### ISSUE TITLE
Use function instead name of module of specific module

### ISSUE THREAD

**Issue by nappex** [Glutexo/onigumo#198]
Currently we map component name to Onigumo module

```elixir
@components = %{:downloader => Onigumo.Downloader}
```
It ll be much nicer to use function instead

```elixir
@components = %{:downloader => fn -> Onigumo.Downloader.main()}
```

**Comment by Glutexo** [comment]
I realized this would be better achieved by a _behavior_. A **component** is not a function (a command), but rather a module with a behavior. Components can be controlled by a supervisor, or in our case, by a CLI interface. As such, it is OK to define those as modules, but defining their behavior (interface) shields us from knowing their iternals.
