### ISSUE TITLE
Parametrize tests

### ISSUE THREAD

**Issue by nappex** [Glutexo/onigumo#59]
Some of tests seem to be similar. For example `download a single URL` and  `download multiple URLs`.

some useful links:
- https://gist.github.com/ramalho/1fa98648737e6bb2d4d4b77a938388f7
- https://dev.to/niku/parameterized-testing-with-exunit-1j3d
- https://gist.github.com/ishikawa/2ad8c415c2a5b6a619e99c18870d6392

**Comment by Glutexo** [comment]
I experimented with parametrized tests in https://github.com/Glutexo/onigumo/pull/50/files#diff-21b6c9a1d317e428c2c4b7e694eba9c7a326a23aa4239d53842ecf92d91b4b80. Please take a look and comment.

**Comment by Glutexo** [comment]
#136  puts the tests in the same _describe_ group. That nicely shows they are related and may become parametrized.
