### ISSUE TITLE
Create a Mix executable

### ISSUE THREAD

**Issue by Glutexo** [Glutexo/onigumo#6]
Can be just a hello world.

**Comment by Glutexo** [comment]
Looks like [Mix.Task](https://hexdocs.pm/mix/Mix.Task.html) is the way to go.

**Comment by nappex** [comment]
I am not sure if I understand it well... 
I've started our project by docs steps, that means start as `iex session`

```shell
cd onigumo
mix compile
iex -S mix
Onigumo.hello()
```
output
```bash
:hello
```

but I supposed we want to run our application as a server on `localhost`, doesn't we?
