### ISSUE TITLE
Follow the right style

### ISSUE THREAD

**Issue by nappex** [Glutexo/onigumo#86]
https://github.com/christopheradams/elixir_style_guide

**Comment by Glutexo** [comment]
With `mix format --check-formatted` in the [workflow](https://github.com/Glutexo/onigumo/blob/a7d27a5985944247016302758644a9c3e9f863a5/.github/workflows/elixir.yml#L32), isn’t the code already following the right style?

**Comment by nappex** [comment]
It should. I dont remember why did I mention it, I think the main purpose was to check it and show a new source of informations

**Comment by Glutexo** [comment]
Okay! I’ll close the issue then. Thank you for the link! It is reasonably short but full of information. I am reading it now, and I‘ll create a pull request if I find something we do differently. Feel free to do the same.
