### ISSUE TITLE
Rename elixir to master

### ISSUE THREAD

**Issue by Glutexo** [Glutexo/onigumo#99]
The transition of this project to Elixir is complete, and its Ruby origin is long gone. For the sake of easiness, let’s rename the main branch back to master.

**Comment by nappex** [comment]
it could be. it is not necessary. Actually, we can rename back to elixir in future if we'd like to, wouldnt we?

**Comment by Glutexo** [comment]
Can you imagine a reason to do so?

**Comment by Glutexo** [comment]
I renamed the _elixir_ branch to _master_. You need to take some steps on your local copy:

```sh
$ git branch -m elixir master
$ git fetch origin
$ git branch -u origin/master master
$ git remote set-head origin -a
```

![Guide](https://user-images.githubusercontent.com/1161096/178349217-ccefe3c0-839d-4156-8d05-d3bfa248bcfb.png)
.

**Comment by Glutexo** [comment]
I also dropped the _ruby_ branch. It served no purpose and was a direct ancestor of the current _master_ with no own commits. While doing that cleanup, I deleted an orphaned _list_urls_ branch from #65. The branch list is now serene.

**Comment by Glutexo** [comment]
Sorry for the inconvenience.

**Comment by Glutexo** [comment]
I made [ruby](https://github.com/Glutexo/onigumo/releases/tag/ruby) a tag for reference.

**Comment by nappex** [comment]
ruby link send me an error

**Comment by Glutexo** [comment]
It shouldn’t! https://github.com/Glutexo/onigumo/tree/ruby is a Git tag!
